// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrSfSQlagta-qp-X1tZHNrwSQcio7o8jk',
    appId: '1:1072934486966:web:c7bf3a64ba83261bb27717',
    messagingSenderId: '1072934486966',
    projectId: 'bok2-a0acb',
    authDomain: 'bok2-a0acb.firebaseapp.com',
    storageBucket: 'bok2-a0acb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9AfDyCmgx_C5ZOb3mpUBhBJe-seMuWG8',
    appId: '1:1072934486966:android:4c61ac4299765dfcb27717',
    messagingSenderId: '1072934486966',
    projectId: 'bok2-a0acb',
    storageBucket: 'bok2-a0acb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT55IkkRm_RmwPxletC4ultIQRqFlNzoo',
    appId: '1:1072934486966:ios:2ce20c244090e350b27717',
    messagingSenderId: '1072934486966',
    projectId: 'bok2-a0acb',
    storageBucket: 'bok2-a0acb.appspot.com',
    iosBundleId: 'com.example.bok2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrSfSQlagta-qp-X1tZHNrwSQcio7o8jk',
    appId: '1:1072934486966:web:63576ba4db956141b27717',
    messagingSenderId: '1072934486966',
    projectId: 'bok2-a0acb',
    authDomain: 'bok2-a0acb.firebaseapp.com',
    storageBucket: 'bok2-a0acb.appspot.com',
  );
}
